[package]
name = "scratchpad"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = { workspace = true }
oqs = { workspace = true, features = ["serde", "vendored"] }
resolution-common = { workspace = true }
