[package]
name = "scratchpad"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
oqs = { version = "0.11.0", features = ["serde", "vendored"] }
resolution-common = { path = "../resolution-common" }
